keys:
  instantnodes: 1uvqK09uDnBF7z3xG1kPjyF9sfN32Cfw
  #test instantnodes: LLHqisIvtdIp8AIRXltYRNFxppFlKGf2
  helius: 5db4069f-b7ca-4c4f-b577-fb7a6f1ce94b
  coingecko: CG-hcevxk12vZbLevzjbb2qCAxD
  pumpportal: dnm3chudd1m6ccbq6dbqaku1athk8vhrcxt6phba6htqjhhqe9d4uc2g85tn8kvdemrpgxa291m6un32d5x3cj3qb8v70mkub9a4wjtp61d4eu1b91r4rdj8f5k36ebuc5u6grj1cwykuf5d6yhht9mu62wbg8hu7euat606xt46gk98h6pyp1het0qgnjqdtcn6mjue98kuf8
