dex:
  raydium: kXS5nkaGSoJBNeqapKd5fzL1rHpFLJopk16dkXJ297r
  lifinity: 82nEEkdjAf2TsVVj189DgRdp7kkQ9Ghs4LqY1gcgbjxn
  solfi: 3nQAMo837oPuGCGELcw2wo7C9hUUchsMWCneiPHFFdur

external_wallet: 4DdrfiDHpmx55i4SPssxVzS9ZaKLb8qr45NKY9Er9nNh
